server.port=8082
spring.application.name=transactionservice
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.datasource.url=${DB_URL_TRANSACTION_SERVICE}
spring.datasource.username=${DB_USERNAME_TRANSACTION_SERVICE}
spring.datasource.password=${DB_PASSWORD_TRANSACTION_SERVICE}

#Client Urls
services.customer.url===${CUSTOMER_SERVICE_URL}

jwt.secret=${JWT_SECRET}

spring.flyway.enabled=true